import { writeFileSync, renameSync, mkdirSync, existsSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { getDatabase } from '../db/index.js';

const PROJECTS_DIR = path.join(process.cwd(), 'data', 'projects');

function ensureDir(): void {
  if (!existsSync(PROJECTS_DIR)) mkdirSync(PROJECTS_DIR, { recursive: true });
}

interface ProjectRow {
  id: string;
  name: string;
  summary: string | null;
  status: string;
  google_links: string;
  effort_estimate: string | null;
  updated_at: string;
}

interface EpicRow {
  id: string;
  title: string;
  description: string | null;
  status: string;
  effort_estimate: string | null;
  sort_order: number;
}

interface TaskRow {
  id: string;
  epic_id: string;
  title: string;
  status: string;
  effort_estimate: string | null;
  sort_order: number;
}

interface MeetingRow {
  label: string | null;
  calendar_event_id: string;
  title: string | null;
  start_time: string | null;
  recurrence: string | null;
}

interface RecommendationRow {
  id: string;
  text: string;
  status: string;
}

interface GoogleLink {
  type: string;
  url: string;
  title: string;
}

export function regenerateProjectMarkdown(projectId: string): void {
  const db = getDatabase();
  const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(projectId) as ProjectRow | undefined;
  if (!project) return;

  const epics = db.prepare(
    'SELECT * FROM epics WHERE project_id = ? ORDER BY sort_order, created_at'
  ).all(projectId) as EpicRow[];

  const tasks = db.prepare(
    'SELECT * FROM tasks WHERE project_id = ? ORDER BY sort_order, created_at'
  ).all(projectId) as TaskRow[];

  const meetings = db.prepare(`
    SELECT pm.label, pm.calendar_event_id, ce.title, ce.start_time, ce.recurrence
    FROM project_meetings pm
    LEFT JOIN calendar_events ce ON pm.calendar_event_id = ce.id
    WHERE pm.project_id = ?
  `).all(projectId) as MeetingRow[];

  const recommendations = db.prepare(
    'SELECT * FROM project_recommendations WHERE project_id = ? ORDER BY created_at'
  ).all(projectId) as RecommendationRow[];

  const tasksByEpic = new Map<string, TaskRow[]>();
  for (const task of tasks) {
    const list = tasksByEpic.get(task.epic_id) ?? [];
    list.push(task);
    tasksByEpic.set(task.epic_id, list);
  }

  let links: GoogleLink[] = [];
  try { links = JSON.parse(project.google_links || '[]'); } catch { /* ignore */ }

  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  lines.push('');
  const meta: string[] = [];
  meta.push(`**Status:** ${project.status}`);
  if (project.effort_estimate) meta.push(`**Effort:** ${project.effort_estimate}`);
  lines.push(meta.join(' | '));
  lines.push('');

  // Summary
  if (project.summary) {
    lines.push('## Summary');
    lines.push(project.summary);
    lines.push('');
  }

  // Links
  if (links.length > 0) {
    lines.push('## Links');
    for (const link of links) {
      const typeLabel = link.type.charAt(0).toUpperCase() + link.type.slice(1);
      lines.push(`- [${link.title}](${link.url}) (Google ${typeLabel})`);
    }
    lines.push('');
  }

  // Meetings
  if (meetings.length > 0) {
    lines.push('## Recurring Meetings');
    for (const m of meetings) {
      const title = m.label || m.title || m.calendar_event_id;
      const time = m.start_time ? ` — ${m.start_time}` : '';
      lines.push(`- ${title}${time}`);
    }
    lines.push('');
  }

  // Recommendations
  const accepted = recommendations.filter((r) => r.status === 'accepted');
  const pending = recommendations.filter((r) => r.status === 'pending');
  if (accepted.length > 0 || pending.length > 0) {
    lines.push('## Recommendations');
    if (accepted.length > 0) {
      lines.push('### Accepted');
      for (const r of accepted) lines.push(`- ${r.text}`);
    }
    if (pending.length > 0) {
      lines.push('### Pending');
      for (const r of pending) lines.push(`- ${r.text}`);
    }
    lines.push('');
  }

  // Epics & Tasks
  if (epics.length > 0) {
    lines.push('## Epics & Tasks');
    lines.push('');
    for (const epic of epics) {
      const effortStr = epic.effort_estimate ? ` — Effort: ${epic.effort_estimate}` : '';
      lines.push(`### ${epic.title} [${epic.status}]${effortStr}`);
      if (epic.description) lines.push(epic.description);
      const epicTasks = tasksByEpic.get(epic.id) ?? [];
      for (const task of epicTasks) {
        const check = task.status === 'done' ? 'x' : ' ';
        const effort = task.effort_estimate ? ` (Effort: ${task.effort_estimate})` : '';
        lines.push(`- [${check}] ${task.title}${effort}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Auto-generated by Orc. Last updated: ${project.updated_at}*`);

  const content = lines.join('\n');
  const filePath = path.join(PROJECTS_DIR, `${projectId}.md`);
  const tmpPath = filePath + '.tmp';

  ensureDir();
  writeFileSync(tmpPath, content, 'utf-8');
  renameSync(tmpPath, filePath);
}

export function deleteProjectMarkdown(projectId: string): void {
  const filePath = path.join(PROJECTS_DIR, `${projectId}.md`);
  try { unlinkSync(filePath); } catch { /* file may not exist */ }
}

export function getProjectMarkdownPath(projectId: string): string {
  return path.join(PROJECTS_DIR, `${projectId}.md`);
}
